/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThongBaoRouteImport } from './routes/thong-bao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HoSoThanhVienRouteImport } from './routes/ho-so.thanh-vien'
import { Route as HoSoMangLuoiRouteImport } from './routes/ho-so.mang-luoi'
import { Route as HoSoLanhDaoRouteImport } from './routes/ho-so.lanh-dao'
import { Route as HoSoCoDongRouteImport } from './routes/ho-so.co-dong'
import { Route as CbttDinhKyIndexRouteImport } from './routes/cbtt.dinh-ky.index'
import { Route as CbttDinhKyMoiRouteImport } from './routes/cbtt.dinh-ky.moi'
import { Route as CbttDinhKyIdRouteImport } from './routes/cbtt.dinh-ky.$id'
import { Route as CbttDinhKyIdSuaRouteImport } from './routes/cbtt.dinh-ky.$id.sua'

const ThongBaoRoute = ThongBaoRouteImport.update({
  id: '/thong-bao',
  path: '/thong-bao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoThanhVienRoute = HoSoThanhVienRouteImport.update({
  id: '/ho-so/thanh-vien',
  path: '/ho-so/thanh-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoMangLuoiRoute = HoSoMangLuoiRouteImport.update({
  id: '/ho-so/mang-luoi',
  path: '/ho-so/mang-luoi',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoLanhDaoRoute = HoSoLanhDaoRouteImport.update({
  id: '/ho-so/lanh-dao',
  path: '/ho-so/lanh-dao',
  getParentRoute: () => rootRouteImport,
} as any)
const HoSoCoDongRoute = HoSoCoDongRouteImport.update({
  id: '/ho-so/co-dong',
  path: '/ho-so/co-dong',
  getParentRoute: () => rootRouteImport,
} as any)
const CbttDinhKyIndexRoute = CbttDinhKyIndexRouteImport.update({
  id: '/cbtt/dinh-ky/',
  path: '/cbtt/dinh-ky/',
  getParentRoute: () => rootRouteImport,
} as any)
const CbttDinhKyMoiRoute = CbttDinhKyMoiRouteImport.update({
  id: '/cbtt/dinh-ky/moi',
  path: '/cbtt/dinh-ky/moi',
  getParentRoute: () => rootRouteImport,
} as any)
const CbttDinhKyIdRoute = CbttDinhKyIdRouteImport.update({
  id: '/cbtt/dinh-ky/$id',
  path: '/cbtt/dinh-ky/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CbttDinhKyIdSuaRoute = CbttDinhKyIdSuaRouteImport.update({
  id: '/sua',
  path: '/sua',
  getParentRoute: () => CbttDinhKyIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/thong-bao': typeof ThongBaoRoute
  '/ho-so/co-dong': typeof HoSoCoDongRoute
  '/ho-so/lanh-dao': typeof HoSoLanhDaoRoute
  '/ho-so/mang-luoi': typeof HoSoMangLuoiRoute
  '/ho-so/thanh-vien': typeof HoSoThanhVienRoute
  '/cbtt/dinh-ky/$id': typeof CbttDinhKyIdRouteWithChildren
  '/cbtt/dinh-ky/moi': typeof CbttDinhKyMoiRoute
  '/cbtt/dinh-ky/': typeof CbttDinhKyIndexRoute
  '/cbtt/dinh-ky/$id/sua': typeof CbttDinhKyIdSuaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/thong-bao': typeof ThongBaoRoute
  '/ho-so/co-dong': typeof HoSoCoDongRoute
  '/ho-so/lanh-dao': typeof HoSoLanhDaoRoute
  '/ho-so/mang-luoi': typeof HoSoMangLuoiRoute
  '/ho-so/thanh-vien': typeof HoSoThanhVienRoute
  '/cbtt/dinh-ky/$id': typeof CbttDinhKyIdRouteWithChildren
  '/cbtt/dinh-ky/moi': typeof CbttDinhKyMoiRoute
  '/cbtt/dinh-ky': typeof CbttDinhKyIndexRoute
  '/cbtt/dinh-ky/$id/sua': typeof CbttDinhKyIdSuaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/thong-bao': typeof ThongBaoRoute
  '/ho-so/co-dong': typeof HoSoCoDongRoute
  '/ho-so/lanh-dao': typeof HoSoLanhDaoRoute
  '/ho-so/mang-luoi': typeof HoSoMangLuoiRoute
  '/ho-so/thanh-vien': typeof HoSoThanhVienRoute
  '/cbtt/dinh-ky/$id': typeof CbttDinhKyIdRouteWithChildren
  '/cbtt/dinh-ky/moi': typeof CbttDinhKyMoiRoute
  '/cbtt/dinh-ky/': typeof CbttDinhKyIndexRoute
  '/cbtt/dinh-ky/$id/sua': typeof CbttDinhKyIdSuaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/thong-bao'
    | '/ho-so/co-dong'
    | '/ho-so/lanh-dao'
    | '/ho-so/mang-luoi'
    | '/ho-so/thanh-vien'
    | '/cbtt/dinh-ky/$id'
    | '/cbtt/dinh-ky/moi'
    | '/cbtt/dinh-ky/'
    | '/cbtt/dinh-ky/$id/sua'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/thong-bao'
    | '/ho-so/co-dong'
    | '/ho-so/lanh-dao'
    | '/ho-so/mang-luoi'
    | '/ho-so/thanh-vien'
    | '/cbtt/dinh-ky/$id'
    | '/cbtt/dinh-ky/moi'
    | '/cbtt/dinh-ky'
    | '/cbtt/dinh-ky/$id/sua'
  id:
    | '__root__'
    | '/'
    | '/thong-bao'
    | '/ho-so/co-dong'
    | '/ho-so/lanh-dao'
    | '/ho-so/mang-luoi'
    | '/ho-so/thanh-vien'
    | '/cbtt/dinh-ky/$id'
    | '/cbtt/dinh-ky/moi'
    | '/cbtt/dinh-ky/'
    | '/cbtt/dinh-ky/$id/sua'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThongBaoRoute: typeof ThongBaoRoute
  HoSoCoDongRoute: typeof HoSoCoDongRoute
  HoSoLanhDaoRoute: typeof HoSoLanhDaoRoute
  HoSoMangLuoiRoute: typeof HoSoMangLuoiRoute
  HoSoThanhVienRoute: typeof HoSoThanhVienRoute
  CbttDinhKyIdRoute: typeof CbttDinhKyIdRouteWithChildren
  CbttDinhKyMoiRoute: typeof CbttDinhKyMoiRoute
  CbttDinhKyIndexRoute: typeof CbttDinhKyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thong-bao': {
      id: '/thong-bao'
      path: '/thong-bao'
      fullPath: '/thong-bao'
      preLoaderRoute: typeof ThongBaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so/thanh-vien': {
      id: '/ho-so/thanh-vien'
      path: '/ho-so/thanh-vien'
      fullPath: '/ho-so/thanh-vien'
      preLoaderRoute: typeof HoSoThanhVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so/mang-luoi': {
      id: '/ho-so/mang-luoi'
      path: '/ho-so/mang-luoi'
      fullPath: '/ho-so/mang-luoi'
      preLoaderRoute: typeof HoSoMangLuoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so/lanh-dao': {
      id: '/ho-so/lanh-dao'
      path: '/ho-so/lanh-dao'
      fullPath: '/ho-so/lanh-dao'
      preLoaderRoute: typeof HoSoLanhDaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-so/co-dong': {
      id: '/ho-so/co-dong'
      path: '/ho-so/co-dong'
      fullPath: '/ho-so/co-dong'
      preLoaderRoute: typeof HoSoCoDongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbtt/dinh-ky/': {
      id: '/cbtt/dinh-ky/'
      path: '/cbtt/dinh-ky'
      fullPath: '/cbtt/dinh-ky/'
      preLoaderRoute: typeof CbttDinhKyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbtt/dinh-ky/moi': {
      id: '/cbtt/dinh-ky/moi'
      path: '/cbtt/dinh-ky/moi'
      fullPath: '/cbtt/dinh-ky/moi'
      preLoaderRoute: typeof CbttDinhKyMoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbtt/dinh-ky/$id': {
      id: '/cbtt/dinh-ky/$id'
      path: '/cbtt/dinh-ky/$id'
      fullPath: '/cbtt/dinh-ky/$id'
      preLoaderRoute: typeof CbttDinhKyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbtt/dinh-ky/$id/sua': {
      id: '/cbtt/dinh-ky/$id/sua'
      path: '/sua'
      fullPath: '/cbtt/dinh-ky/$id/sua'
      preLoaderRoute: typeof CbttDinhKyIdSuaRouteImport
      parentRoute: typeof CbttDinhKyIdRoute
    }
  }
}

interface CbttDinhKyIdRouteChildren {
  CbttDinhKyIdSuaRoute: typeof CbttDinhKyIdSuaRoute
}

const CbttDinhKyIdRouteChildren: CbttDinhKyIdRouteChildren = {
  CbttDinhKyIdSuaRoute: CbttDinhKyIdSuaRoute,
}

const CbttDinhKyIdRouteWithChildren = CbttDinhKyIdRoute._addFileChildren(
  CbttDinhKyIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThongBaoRoute: ThongBaoRoute,
  HoSoCoDongRoute: HoSoCoDongRoute,
  HoSoLanhDaoRoute: HoSoLanhDaoRoute,
  HoSoMangLuoiRoute: HoSoMangLuoiRoute,
  HoSoThanhVienRoute: HoSoThanhVienRoute,
  CbttDinhKyIdRoute: CbttDinhKyIdRouteWithChildren,
  CbttDinhKyMoiRoute: CbttDinhKyMoiRoute,
  CbttDinhKyIndexRoute: CbttDinhKyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
